app:
  port: 8194
  debug: false
  key: dify-sandbox
max_workers: 4
max_requests: 50
worker_timeout: 15
python_path: /usr/local/bin/python3
enable_network: true
enable_preload: false
allowed_syscalls: []
proxy:
  socks5: ''
  http: 'http://ssrf_proxy:3128'
  https: 'http://ssrf_proxy:3128'
